### ISSUE TITLE
dial value formatting inconsistent

### ISSUE THREAD

**Issue by bosepchuk** [openenergymonitor/emoncms3#100]
As seen in the screenshot below, positive values appear to be rounded to the nearest whole number once they are greater than 10. But the same formatting seems to be absent for negative values.

Bug or not? I'll let you decide.

Great software, by the way!

![capture.jpg](https://f.cloud.github.com/assets/2993457/1478/c4eaf4a6-40e5-11e2-8e71-6c34e663f00b.jpg)

**Comment by TrystanLea** [comment]
Thanks, probably oversight? will try an fix it in the https://github.com/emoncms/emoncms repo

**Comment by bosepchuk** [comment]
You're welcome.

Great project!
