### ISSUE TITLE
Add multiple languages support.

### ISSUE THREAD

**Issue by TrystanLea** [openenergymonitor/emoncms3#23]
A start has been made on this, but it may be better to implement it differently using gettext: http://mel.melaxis.com/devblog/2005/08/06/localizing-php-web-sites-using-gettext/

**Comment by alco28** [comment]
Hi Trystan, I can made an Dutch Translation on the emoncms , is it useful to do that (by copy the EN dir and translate all the php text strings)

**Comment by ildemartinez** [comment]
Hi alco28!!

the next release will support .po and .mo files translation system. You could get .po file from https://github.com/openenergymonitor/emoncms3/tree/dev/locale/es_ES/LC_MESSAGES and use the PoEditor from http://www.poedit.net/ to translate it to Dutch. It could be really fantastic get Dutch translations!!!

Best regards

**Comment by alco28** [comment]
I made an local repository and made an nl_NL folder with an copy of those files. now editing it to Dutch. and will commit it back in a few days!

**Comment by alco28** [comment]
Commit an dutch language pack last night for nl_NL (Netherlands, language Dutch) we only speak Dutch here so there isn't an second language pack. I also will translate it to nl_BE (Belgium, language Dutch) because it's ferry similar to my native language.

**Comment by TrystanLea** [comment]
We have now completed the multilanguage implementation using gettext, there's a page on installation on ubuntu here: http://openenergymonitor.org/emon/node/809 documentation will be fully linked through at the dev-master merge branch release point
