### ISSUE TITLE
Optimize for variety of screen size, including mobiles / tablets on the one side and larger screens on the other.

### ISSUE THREAD

**Issue by TrystanLea** [openenergymonitor/emoncms3#26]
A todo feature request, copied from feature plans and discussion on the openenergymonitor forums: http://openenergymonitor.org/emon/node/296

What's the best way to do this with dashboards?. Maybe it would be good to have two types of dashboards mobile optimised dashboards and dashboards for larger screens.

**Comment by ildemartinez** [comment]
Hi

I think the best way to do that Is have a responsible css template to use in dashboard. You could have diferents css design all based on responsible philosophy. With one css will look fine in all devices.

Ckeditor Is prepared to use different css files and a new field on dashboard table could have the directory name of each css template.

Take a look at http://speckyboy.com/2011/11/17/15-responsive-css-frameworks-worth-considering/

I think Skeleton Is fine so we should adapt actual css to that

**Comment by ildemartinez** [comment]
I found bootstrap the best css styles for responsible design

take a look at: http://twitter.github.com/bootstrap/scaffolding.html

should i try to integrate it with emoncms?

Best regards
ilde

**Comment by TrystanLea** [comment]
Update: this has now been implemented by Ilde and is working really well.
