### ISSUE TITLE
Documentation Idea: common energy monitoring web app dev challenges

### ISSUE THREAD

**Issue by TrystanLea** [openenergymonitor/emoncms3#30]
This would be a section of the documentation that would explore common energy monitoring web app dev challenges in general such as:
- API Design ( REST interface)
- Data Processing: Power to kWh/d, histogram analysis
- Data Storage: MYSQL, table per feed, unix time indexed data
- Visualisation: Multigraph, Zooming through big data, LOD level of detail, AJAX realtime.

This would give some background as to why various elements in emoncms have been coded the way they have and also hopefully help others interested in developing other open source web applications from scratch how to solve similar challenges.

**Comment by alco28** [comment]
Trystan,

Is there some documentation about the Visuals that we can use? I'm struggling with the <div> options from the Dails (like type="6" and how to set the needle center value) and zoom graphics.
