### ISSUE TITLE
User dashboard URL access

### ISSUE THREAD

**Issue by TrystanLea** [openenergymonitor/emoncms3#38]
Feature idea:  a nice URL system where a user can access their account via:

emoncms/username

If a user shared a dashboard publicly anyone can access the users dashboard via their username otherwise a login form is supplied.

To see how this might look its easy to add a few lines of code. In index.php add:

  if ($output == null)
  {
    $userid = get_user_id($controller);
    if ($userid) {
      $session['userid'] = $userid;
      $session['read'] = 1; 
      $action = "run"; 
      $output = controller("dashboard");
    }
  }

just below the line   $output = controller($controller);

The next step would be to have dashboard pages linked through to the url ie: emoncms/username/solar

**Comment by jsidrach** [comment]
I've been looking how to do this...

http://www.yourhtmlsource.com/sitemanagement/urlrewriting.html
http://stackoverflow.com/questions/3721390/create-personal-page-for-every-user-php

It doesn't seem to be so hard

**Comment by TrystanLea** [comment]
Hello Juan

Sorry for the slow reply. Yes using modrewrite is how much of the arguments such as controller and action are passed already.

So we have 

emoncms3/user/view

is converted too:

emoncms3?q=user/view

the q string is then split into the $controller and $action variable.

**Comment by TrystanLea** [comment]
this feature is now implemented in the latest commit
