### ISSUE TITLE
MySQL date convertion into Javascript date

### ISSUE THREAD

**Issue by bgaultier** [openenergymonitor/emoncms3#4]
Hi there,

Since 5831f49f8f there is a little problem with  **Views/feed/list_view.php** and **Views/input/list_view.php**:

This peace of code is not working :
`var update = (new Date(feeds[z][3])).getTime();`
since Date() can not take MySQL raw date as an arg.

A a small part of the answer here : http://stackoverflow.com/questions/1765803/convert-a-mysql-date-to-javascript-date

Thanks a lot for your amazing work !

**Comment by bgaultier** [comment]
There is also a missing **;** at
`var hour = secs/3600`

**Comment by TrystanLea** [comment]
Thankyou Baptiste, that's strange as it does seem to work here? it counts up in time after it receives an update and the time is correct.

I have added the comma. thanks a lot.

**Comment by bgaultier** [comment]
Hi Trystan,

I finally found what was wrong. I'm using Firefox and it seems that the javascript engine does not support **Date("YYYY-MM-DD hh:mm:ss")** when creating a Date Object while there is no problem when rendering the same code on Chromium.

**Comment by TrystanLea** [comment]
I have finally fixed it, I have changed the time variable sent from api from a date string to a timestamp which is now consistent with how time is send in get_feed_data. I have it working here in both browsers.

Thanks for flagging the issue up!

**Comment by bgaultier** [comment]
Hi Trystan,
It works like a charm, thanks for your amazing work (as usual) !
