### ISSUE TITLE
Add csv export capability.

### ISSUE THREAD

**Issue by PowerMeter** [openenergymonitor/emoncms3#76]
I'd suggest an export wizard ; though there's a decent amount of work in this. Alternatively, you will need to give people using the emoncms.org site the option to get their data.... Don't think you want to let them logon to the db so the export option is the way to go. Phase 1 might just be one years data, csv format [one click export] ; phase 2 might be the whole wizard?

**Comment by TrystanLea** [comment]
This is now implemented :) openenergymonitor.blogspot.co.uk/2012/09/data-portability-version-1-complete.html

**Comment by ildemartinez** [comment]
Great feature!!!

**Comment by PowerMeter** [comment]
That's a great feature...... thanks. very cool.

**Comment by TrystanLea** [comment]
Yes Im really happy with this it makes keeping a local copy of the remote data really easy and it can be kept up to date by only downloading the changes.
