### ISSUE TITLE
Manual data entry, as a separate feed.

### ISSUE THREAD

**Issue by PowerMeter** [openenergymonitor/emoncms3#77]
My local brewer would like to be able to enter the number of hectolitres of beer done each month, manually, and then have the €/hL cost show up in the dashboard, over time. This is where emoncms gets into delivering kpi's to business. Right now, business don't really know this key performance indicator and it's something that is vital to them.

**Comment by mattwire** [comment]
This is something I'd like for my water and historical energy too.  But I think in your case you can get the data in easily with some scripting and the API (note the use of the time var):
https://hostname/api/post?apikey=TOKEN&time=NNNNNNNNNN&json={var1:200.2}

**Comment by PowerMeter** [comment]
True; that's the most practical approach - this data will be only entered on a monthly basis to begin with.
