### ISSUE TITLE
Insert datapoints via SQL ?

### ISSUE THREAD

**Issue by emdeex** [openenergymonitor/emoncms3#80]
Hi All,

I'm just throwing this out there, to see if someone can help steer me in right direction.

I've got three years of historical timestamped kWh data, for 36 meters, at 15min intervals.  I want to get it into emonCMS.

I can transform it into the format expected in emonCMS database: "unixtimestamp", "value".

I can make 36 tables, named feed_1 to feed_36, and insert the data.

I can insert 36 entries into the table "feeds", with a datatype of 3.

What next?  I'm not sure how the other feed types get generated, like powerkwhd.

I'll give it a bash tonight and see what happens.... any info appreciated.  I'll fork the project and contribute anything useful I come across.

regards,
Murray

**Comment by emdeex** [comment]
I created a table for the powerkwhd, by grouping my existing data by day, and copied that over as a table with the relevant feed ID.

The data is there, but the visualizations aren't all working yet.

In the table "feeds", how is the datatype defined?

**Comment by emdeex** [comment]
Another idea to get the data in is write a curl script to post my data in via the API, but I need to use a historical timestamp. 

Can I use this?

https://hostname/api/post?apikey=TOKEN&time:NNNNNNNN&json={var1:200.2}

**Comment by mattwire** [comment]
You are correct.  You can use a time flag in the API url like so:
https://hostname/api/post?apikey=TOKEN&time=NNNNNNNNNN&json={var1:200.2}

(Note use = and not : sign).

**Comment by emdeex** [comment]
oh _groan_, the time is an epoch unixtime?

Can someone point to the code where I can change the expected format to be a string time ?
