### ISSUE TITLE
Unable to install update database

### ISSUE THREAD

**Issue by gubagu** [openenergymonitor/emoncms3#82]
I followed the installation manual on the website
1.Created the databse
2. Uncommented   $runnable = TRUE;
3. Run http://localhost/openenergymonitor/setup.php 
and got the followoing

 Fatal error: Call to undefined function _() in C:\wamp_Sites\openenergymonitor\setup.php on line 22

Class missing ?

Cheers Guby

**Comment by ildemartinez** [comment]
Yes, you need to install the gettext php module.

More info at: http://www.php.net/manual/en/book.gettext.php

Hope it fix
Best regards

**Comment by gubagu** [comment]
Thanks a lot for your swift reply man!
I had gettext installed but not enabled. Unfortunately my test machine (WAMPSERVER) has version of apache that crashes if geettext is enabled. I will setup Linux test box with the last available and inform you if that solves the problem.
btw what version of LAMP/WAMP are guys testing on ? 

Omoncms3 - Great Idea wonderful work !
Keep it up !

**Comment by ildemartinez** [comment]
Hi

i am using wampserver 2.2 from www.wampserver.com over windows7 for dev pourpose. Activating php_gettext from php extensions and rewrite_module from apache modules all using wampserver menu icons.

All the best
ilde
