### ISSUE TITLE
iframe mistakenly pointing to LAN IP for publicly available graphs

### ISSUE THREAD

**Issue by bosepchuk** [openenergymonitor/emoncms3#99]
My publicly available graphs are not displaying when I try to access them from the internet because the source location for the iframe that displays them is pointing to my LAN IP instead of my external URL.

It is interesting to note that if I login, I can view my graphs from the dashboard page just fine when I am accessing the internet.

I hope this screenshot is useful...

![capture.jpg](https://f.cloud.github.com/assets/2993457/1472/6bfcac64-40e4-11e2-8d9f-902023176e51.jpg)

**Comment by TrystanLea** [comment]
Hello, are you using the emoncms version from github.com/emoncms/emoncms that is the latest version, I should probably make it clearer here that this version is old

**Comment by bosepchuk** [comment]
Hi,

It looks like I might be running an older version based on the differences
between the files on github and my server. I followed the links from
http://openenergymonitor.org and installed in October, 2012.

I can't seem to see a version or build number anywhere. Is there a way to
tell for sure what version I am running?

**Comment by bosepchuk** [comment]
The zip I downloaded is actually: openenergymonitor-emoncms3-0d2c912.zip

Does that help?

**Comment by TrystanLea** [comment]
Sorry for the slow reply, yes thats the old version. Can you try downloading the new version? just point it to the database location of your current emoncms database then login with the first user you created, hopefully the admin tab will appear in the top right hand corner. let me know if you get to that point.

**Comment by bosepchuk** [comment]
Thanks. I'll try upgrading after Christmas.

**Comment by jonbev** [comment]
I have this same issue with the up to date version. I have just edited the content field in the database so that the iframe src is relative rather than the fully qualified path.

**Comment by bosepchuk** [comment]
Thanks. That works for me.

I replaced the lan ip address of my server with my public facing domain
name mapped to that server in the contents field of the dashboard table.
And it works.
